### ISSUE TITLE
Salut!

### ISSUE THREAD

**Issue by job1138** [warezcmpt/JRabbitBox#1]
Le script m'installe bien la bonobox et un peu de sécu, postfix mais c'est tout. J'aurais aimer pouvoir faire tourner plex et wordpress... des idées? Merci

**Comment by warezcmpt** [comment]
Pour plex ca marche chez moi, faut l'activer pour etre visible a l'exterieur du serveur grace a Lxde & Vnc:
Ipserveur:32400/web

Pour wordpress j'y travaille...

Envoyé par TypeApp



Le 28 juin 2016 10:16, à 10:16, job1138 <notifications@github.com> a écrit:

**Comment by job1138** [comment]
ok!!! Merci pour ta répose, super boulot pour un noob comme moi. Je suis ça de prêt!!!

**Comment by job1138** [comment]
Ps : ton site est malade :p

**Comment by warezcmpt** [comment]
Ouai mon dédié est parti en couille, j'ai pas su remettre  ca en place (noob aussi) donc formatage et migration du script sur github :)
Ca avance petit a petie...

Envoyé par TypeApp



Le 28 juin 2016 11:34, à 11:34, job1138 <notifications@github.com> a écrit:
